name: perl
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  ubuntu:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        perl-version: ['5.10', '5.14', '5.20']
        perl-threaded: [false]
        include:
          - perl-version: '5.30'
            os: ubuntu-latest
            release-test: true
            coverage: true
          - perl-version: '5.30'
            os: ubuntu-latest
            perl-threaded: true
    steps:
      - uses: actions/checkout@v2
      - name: Ubuntu packages
        run: sudo apt-get -y update && sudo apt-get -y install libfftw3-dev
      - uses: shogo82148/actions-setup-perl@v1
        with:
          distribution: strawberry # ignored non-windows
          perl-version: ${{ matrix.perl-version }}
          multi-thread: ${{ matrix.perl-threaded }}
      - run: cpanm -n PDL::Core::Dev IPC::Run # configure requires
      - run: cpanm -n --installdeps .
      - run: perl -V
      - name: Run release tests # before others as may install useful stuff
        if: ${{ matrix.release-test }}
        env:
          RELEASE_TESTING: 1
        run: |
          cpanm -n --installdeps --with-develop .
          prove -lr xt
      - name: Run tests (no coverage)
        if: ${{ !matrix.coverage }}
        run: perl Makefile.PL && HARNESS_OPTIONS='j4' make test
      - name: Run tests (with coverage)
        if: ${{ matrix.coverage }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cpanm -n Devel::Cover::Report::Coveralls
          cpanm git://github.com/mohawk2/Devel--Cover.git@deepdirs
          HARNESS_OPTIONS='j4' cover -test -relative_only -gcov_chdir -report Coveralls
